### PR TITLE
global config, sound disable, alpha channel for widgets.

### PR DESCRIPTION
**Pull request by JDat**
*) global config in config.py
*) sound can be disabled from config.py
*) button, elbow and tab images now have alpha channel
*) addec alha for button, elbow and tab
*) added home button to remove wigets form main screen.
   button mispaced to test alpha funcionality
   added elbow to test elbow alpha functionality
*) pressing enegy is the same as logout to test event handler
*) authorise screen in debug mode have exit button X

### CODE REVIEW

**Comment by tobykurien** [comment]
Hi @JDat thank you so much for the pull request! Here are some comments on the changes:

- The alpha channel on button.png looks good
- Happy with the global config
- Sound disabling requires putting `if config.SOUND` around every sound call which is messy and error-prone, and in addition still initializes the mixer. Ideally this needs to be handled in the UI itself (and passed as an init parameter) so that in the screens, we can just call `ui.play('asset.wav')` and if it's disabled, it ignores the call.

**Comment by MalmarPadecain** [comment]
I'd be willing to try my hand at wrapping the sound stuff. 
I am however quite new to github and git in general. How do I contribute to an existing Pull Request?

**Comment by dgw** [comment]
@MalmarPadecain You'll have to open your own PR, since GitHub (perhaps obviously) won't let you push to someone else's repo. (Without permission, but it would be a battle to get in touch with @JDat and become a collaborator on this PR's source repo.)

So, if you want to build off of this, clone this repo (tobykurien/rpi_lcars) and then add JDat's repo as a remote so you can `git checkout` this branch as a starting point. Once you have something, open a new pull request (referencing this one just so @tobykurien can keep track of what's happening).

**Comment by tobykurien** [comment]
@MalmarPadecain I have pulled the changes into a new branch called JDat-master, so you can now clone this repo, work on the changes in that branch and send pull requests for that branch. Should make things easier.

**Pull request closed without merging**
