### PR TITLE
Feature/show actual ip address

### PR DESCRIPTION
**Pull request by glindsey**
Replaces the fake IP address with the real one obtained from the system.

### CODE REVIEW

**Comment by dgw** [comment]
There are a number of IP helper services listed in the source code for `ipgetter`, if you don't want to add that module as a dependency. https://github.com/phoemur/ipgetter/blob/master/ipgetter.py

**Comment by glindsey** [comment]
I've added exception handling for the code to properly handle having no network connection. I haven't tested what happens if it is connected to a LAN but doesn't have a route to the internet, but if that results in a "host unreachable" error it should print "LOCAL ONLY" as the address for now. That's not ideal but at least it doesn't crash in those instances.

**Comment by tobykurien** [comment]
The main reason for showing the IP address on the panel is to allow local ssh access. This means we are only interested in the local IP, and in the case of home automation, we probably don't even want the panel connected to the internet directly.

With that in mind, the "local only" error ends up defeating the purpose. I wonder if a `subprocess(...)` call to `ifconfig` might not be a better option? We can ignore the `127.0.0.1` address, but show all other addresses, since there may be more than one interface connected (e.g. ethernet plus the built-in WiFi).

**Comment by glindsey** [comment]
That's a fantastic point. I've updated the code to another example I found (in that same SO post, in fact). It uses the `psutil` library to do basically what you've outlined above. Only caveat right now is that the IP list will usually be misaligned on the screen since there's no support for right-aligned text yet, but that's an easily fixable cosmetic issue to be addressed separately.

**Comment by tobykurien** [comment]
Thanks for your work on this, it's looking good! Please also update `requirements.txt` with the new dependency and also `setup.sh` with an `apt-get` alternative (perhaps `python-psutil`?) The idea is that someone can just clone this repo onto a fresh install of rasbian, run `setup.sh` and then `run.sh` it.

**Comment by glindsey** [comment]
Hey, I’m sorry, was planning to do what you asked, but then had a busy period at work and now am on vacation!

**Pull request merged**
