### PR TITLE
Add side navigation buttons, functional PIN authentication

### PR DESCRIPTION
**Pull request by MS3FGX**
Not sure if this is suitable for merging given the goals of your own personal project, but these are some changes I've made on my own fork and thought at the very least perhaps others looking at the code may be interested in seeing it.

I've added a new asset and some switches in LcarsButton so that it can handle not only the rounded buttons from the original code, but also square "navigation" buttons on the side of the display (which in the original code are just mockups). You need to add a "type" argument when calling LcarsButton (currently either "btn" or "nav"), but its operation is otherwise the same as before. 

I've also renamed the existing mock authentication to "Idle", and added in a working authentication screen between it and the main screen (which I've again named authorize.py). This is by no means meant to be an actually secure method of authentication, of course. The PIN can be specified in the authorize.py file, and I tried to use comments to make it clear what needs to be modified. Default PIN is "1234"

### CODE REVIEW

**Comment by tobykurien** [comment]
Thanks for this @MS3FGX - I'll have a look and merge. I would certainly prefer that ```LcarsButton``` didn't add a new parameter - as this breaks all the code currently using it (yes, I am using this project in other projects too). It would be better if you created ```LcarsSideButton``` (for example, I actually called them ```LcarsBlock...``` for the various sizes) which just extends the original. I would also prefer that the unused code wasn't removed (I'm happy to move them to another file) as they can be used later, e.g. ```LcarsElbow``` allows the elbow element to be clickable and ```LcarsTab``` is needed on more complex screens.

**Comment by tobykurien** [comment]
I really like the authorization screen, will manually merge that in. Thanks!

**Comment by dgw** [comment]
WRT the new parameter to `LcarsButton`, why not make `shape` a kwarg that defaults to 'btn'? That would avoid breaking existing code, but still add the functionality.

**Comment by tobykurien** [comment]
Thanks @dgw I have added a "rectSize" parameter which, if specified, makes a rectangular button. I've also then implemented ```LcarsBlockLarge```, ```LcarsBlockMedium```, and ```LcarsBlockSmall``` for the left navigation.

**Pull request closed without merging**
